# Generated by Django 5.2.17 on 2026-09-14 09:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('length_mm', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('width_mm', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('height_mm', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('max_weight_g', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('height_mm__gt', 0), ('length_mm__gt', 0), ('width_mm__gt', 0)), name='box_positive_dimensions'), models.CheckConstraint(condition=models.Q(('cost__gte', 0), ('max_weight_g__gt', 0)), name='box_valid_weight_cost')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('length_mm', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('width_mm', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('height_mm', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('weight_g', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('height_mm__gt', 0), ('length_mm__gt', 0), ('width_mm__gt', 0)), name='product_positive_dimensions'), models.CheckConstraint(condition=models.Q(('weight_g__gt', 0)), name='product_positive_weight')],
            },
        ),
    ]
